config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  # devise_for :users, controllers: {
  #   registrations: 'registrations'
  # }

  root 'pages#home'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'

  get '/sliders/:short_code', to: 'sliders#show'

  namespace :admin do
    resources :sliders, only: [:index, :show]
    resources :request_logs, only: [:index]
    resources :track_logs, only: [:index]
    resources :users, only: [:index] do
      member do
        get 'send_expired_outreach', action: :send_expired_outreach
      end
    end
  end

  namespace :dashboard do
    get '/sliders', to: 'sliders#index'
    get '/sliders/new', to: 'sliders#new', as: :new_slider
    get '/sliders/:short_code', to: 'sliders#edit', as: :edit_slider
    patch '/sliders/:short_code', to: 'sliders#update', as: :update_slider
    delete '/sliders/:short_code', to: 'sliders#destroy', as: :destroy_slider

    post '/sliders/:short_code/slide_create', to: 'sliders#slide_create', as: :slide_create
    get '/sliders/:short_code/slide_destroy/:slide_id', to: 'sliders#slide_destroy', as: :slide_destroy
    post '/sliders/:short_code/slides_update', to: 'sliders#slides_update', as: :slides_update

    get '/sliders/:short_code/slides/new', to: 'sliders/slides#new', as: :sliders_slide_new
    post '/sliders/:short_code/slides', to: 'sliders/slides#create', as: :sliders_slide
    get '/sliders/:short_code/slides/:id', to: 'sliders/slides#edit', as: :sliders_slide_edit
    patch '/sliders/:short_code/slides/:id', to: 'sliders/slides#update', as: :sliders_slide_update

    get '/subscription/checkout', to: 'subscription#checkout', as: :subscription_checkout
    get '/subscription/success', to: 'subscription#success', as: :subscription_success

    resource :account, only: [:show, :update], controller: 'account'
  end

  post '/track', to: 'track#create'
  get '/unsubscribe/:user_id', to: 'unsubscriptions#create', as: :unsubscribe
  get '/unsubscribe/:user_id/success', to: 'unsubscriptions#show', as: :unsubscribe_success

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/slider.rb
# == Schema Information
#
# Table name: sliders
#
#  id                 :uuid             not null, primary key
#  user_id            :uuid
#  title              :string
#  short_code         :string
#  settings           :jsonb
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  request_logs_count :integer          default(0)
#  width              :string           default("1600")
#  height             :string           default("250")
#  mode               :string           default("linear")
#  speed              :string           default("500")
#  auto_enabled       :boolean          default(FALSE)
#  auto_interval      :string           default("2000")
#  controls_enabled   :boolean          default(TRUE)
#  pager_enabled      :boolean          default(TRUE)
#  version            :integer
#  track_logs_count   :integer          default(0)
#
# Indexes
#
#  index_sliders_on_short_code  (short_code) UNIQUE
#

class Slider < ActiveRecord::Base
  has_many :slides, -> { order(weight: :asc) }, dependent: :destroy
  has_many :request_logs
  has_many :track_logs
  belongs_to :user

  before_create :set_short_code

  def self.ransackable_attributes(auth_object = nil)
    ['short_code']
  end

  private

  def set_short_code
    self.short_code = loop do
      random_short_code = ('a'..'z').to_a.shuffle[0,6].join
      break random_short_code unless Slider.exists?(short_code: random_short_code)
    end
  end
end

app/controllers/admin/sliders_controller.rb
class Admin::SlidersController < AdminController
  def index
    @sort = params[:sort] || 'date'
    @direction = params[:dir] || 'desc'

    @sliders = Slider
      .includes(:user)
      .references(:user)
      .where('users.id IS NOT NULL')
      .page(params[:page])
      .per(50)

    if @sort == 'date'
      @sliders = @sliders.order(created_at: @direction)
    elsif @sort == 'requests'
      @sliders = @sliders.order(request_logs_count: @direction)
    elsif @sort == 'tracks'
      @sliders = @sliders.order(track_logs_count: @direction)
    end
  end

  def show
    @slider = Slider.find(params[:id])
    @slides = @slider.slides.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/dashboard/account_controller.rb
class Dashboard::AccountController < DashboardController
  def show
  end

  def update
    @user = current_user

    if @user.update(user_params)
      bypass_sign_in(@user)
      redirect_to dashboard_account_path, notice: 'Successfully saved.'
    else
      redirect_to dashboard_account_path, alert: 'Could not save.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/dashboard/sliders/slides_controller.rb
class Dashboard::Sliders::SlidesController < DashboardController
  def new
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = Slide.new
  end

  def create
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.new(slide_params)

    if @slide.save
      redirect_to dashboard_edit_slider_path(@slider.short_code), notice: 'Slide created.'
    else
      render :new
    end
  end

  def edit
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.find(params[:id])
  end

  def update
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.find(params[:id])

    if @slide.update(slide_params)
      redirect_to dashboard_edit_slider_path(@slider.short_code), notice: 'Slide updated.'
    else
      render :edit
    end
  end

  private

  def slide_params
    params.require(:slide).permit(:image, :url)
  end
end

app/controllers/dashboard/sliders_controller.rb
class Dashboard::SlidersController < DashboardController
  def index
    @sliders = current_user.sliders
  end

  def edit
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  def update
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slider.update!(slider_params)
  end

  def new
    @slider = current_user.sliders.create!

    redirect_to dashboard_edit_slider_path(@slider.short_code)
  end

  def destroy
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slider.destroy!
    redirect_to dashboard_sliders_path, notice: "Slider #{@slider.short_code} was deleted."
  end

  def slide_destroy
    slide = Slide.find(params[:slide_id])
    slide.destroy!

    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  def slides_update
    params[:slides].each_with_index do |slide_id, index|
      slide = Slide.find(slide_id)

      slide.update!(weight: index)
    end

    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  private

  def slider_params
    params.require(:slider).permit!
  end

  def slide_params
    params.require(:slide).permit(:content, :weight, :image, :slider_id)
  end
end

app/controllers/dashboard/subscription_controller.rb
class Dashboard::SubscriptionController < DashboardController
  def checkout
    stripe_portal = Stripe::Checkout::Session.create({
      cancel_url: dashboard_account_url,
      success_url: ENV['APP_HOST'] + '/dashboard/subscription/success?session_id={CHECKOUT_SESSION_ID}',
      line_items: [
        { price: ENV['STRIPE_PRICE_ID'], quantity: 1 },
      ],
      mode: 'payment',
      customer_email: current_user.email
    })

    redirect_to(stripe_portal[:url], allow_other_host: true)
  end

  def success
    stripe_session = Stripe::Checkout::Session.retrieve(params[:session_id])

    current_user.update!(
      stripe_customer_id: stripe_session[:customer],
      stripe_transaction_id: stripe_session[:payment_intent],
      stripe_purchased_at: Time.now,
      status: 'paid'
    )

    begin
      UserMailer.with(user: current_user).payment_success.deliver_now
    rescue => e
      Sentry.capture_exception(e)
    end

    begin
      AdminMailer.with(user: current_user).new_payment.deliver_now
    rescue => e
      Sentry.capture_exception(e)
    end

    redirect_to dashboard_sliders_path, notice: 'Thank you for purchasing SliderUI!'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_subscription

  layout 'dashboard'

  private

  def ensure_subscription
    return if current_user.active?

    @checkout_url = dashboard_subscription_checkout_path
  end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  include ActionView::Helpers::TagHelper
  skip_before_action :verify_authenticity_token

  def show
    @short_code = params[:short_code]
    @slider = Slider.find_by(short_code: @short_code)
    @inactive_user = @slider.present? && @slider.user && !@slider.user.active?

    begin
      RequestLog.create!(
        slider: @slider,
        user: @slider.user,
        referrer: request.referrer
      )
    rescue => e
      # Oops.
    end
  end
end

app/views/dashboard/sliders/_preview.html.erb
<div id="slider-preview">
  <div data-slider-id="<%= slider.short_code %>">
    <%= render 'slider_code', slider: slider %>
  </div>
</div>

app/views/dashboard/sliders/_sign_in.html.erb
<% if @session_error %>
  <div class="rounded-md bg-red-50 p-4 mb-8 border border-red-300">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <div class="text-sm text-red-700">
          <%= @session_error %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="mt-3 text-center sm:mt-5">
  <div class="flex flex-col items-center">
    <h3 class="text-xl font-semibold text-gray-900" id="modal-title">Login to Your Account</h3>
  </div>
</div>

<div class="flex min-h-full flex-col justify-center px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <%= form_for(@user, url: dashboard_slider_session_create_path(short_code: @slider.short_code), remote: true, html: { class: 'space-y-6' }) do |f| %>
      <div>
        <%= f.label :email, 'Email', class: 'block text-sm font-medium leading-6 text-gray-900' %>
        <div class="mt-2">
          <%= f.text_field :email, type: :email, required: true, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
        </div>
      </div>

      <div>
        <%= f.label :password, 'Password', class: 'block text-sm font-medium leading-6 text-gray-900' %>
        <div class="mt-2">
          <%= f.password_field :password, required: true, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
        </div>
      </div>

      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
          Login
        </button>
      </div>
    <% end %>

    <p class="mt-10 text-center text-sm text-gray-500">
      Don't have an account?
      <button @click="form = 'signup'" class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">
        Click here to create an account
      </button>
    </p>
  </div>
</div>

app/views/dashboard/sliders/_sign_up.html.erb
<% if @user.errors.any? %>
  <div class="rounded-md bg-red-50 p-4 mb-8 border border-red-300">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <div class="text-sm text-red-700">
          <%= @user.errors.full_messages.first %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="mt-3 sm:mt-5">
  <div class="sm:mx-auto sm:w-full sm:max-w-lg px-6 lg:px-16">
    <h3 class="text-xl font-semibold text-gray-900 mb-3 text-center">
      Create an Account
    </h3>
    <ul class="text-sm text-gray-500">
      <li class="flex gap-x-2 items-center">
        <svg class="h-7 w-5 flex-none text-indigo-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
        </svg>
        Update your slider settings after installing
      </li>

      <li class="flex gap-x-2 items-center">
        <svg class="h-7 w-5 flex-none text-indigo-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
        </svg>
        Create and manange multiple sliders
      </li>

      <li class="flex gap-x-2 items-center">
        <svg class="h-7 w-5 flex-none text-indigo-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
        </svg>
        Access live support after installing a slider
      </li>
    </ul>
  </div>
</div>

<div class="flex min-h-full flex-col justify-center px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-lg">
    <%= form_for(@user, url: dashboard_slider_user_create_path(short_code: @slider.short_code), remote: true, html: { class: 'space-y-6' }) do |f| %>
      <div>
        <%= f.label :email, 'Email', class: 'block text-sm font-medium leading-6 text-gray-900' %>
        <div class="mt-2">
          <%= f.text_field :email, type: :email, required: true, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
        </div>
      </div>

      <div>
        <%= f.label :password, 'Password', class: 'block text-sm font-medium leading-6 text-gray-900' %>
        <div class="mt-2">
          <%= f.password_field :password, required: true, class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
        </div>
      </div>

      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
          Create Account
        </button>
      </div>
    <% end %>

    <p class="mt-10 text-center text-sm text-gray-500">
      Already have an account?
      <button @click="form = 'signin'" class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">
        Click here to login
      </button>
    </p>
  </div>
</div>

app/views/dashboard/sliders/_slide_list.html.erb
<div id="slide-list" class="divide-y">
  <% slides.each do |slide| %>
    <div class="flex gap-2 py-3 bg-white" data-slide-id="<%= slide.id %>">
      <div
        style="background-image: url(<%= slide.image.url %>)"
        class="w-24 h-16 bg-center bg-cover rounded-md"
      ></div>

      <div class="flex gap-2 items-center">
        <%= link_to dashboard_sliders_slide_edit_path(id: slide.id) do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-500">
            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
          </svg>

          <div class="sr-only">
            Edit Slide
          </div>
        <% end %>

        <%= link_to dashboard_slide_destroy_path(slide_id: slide.id),
            data: { confirm: 'Are you sure?' },
            remote: true do
        %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-500">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        <% end %>

        <div class="cursor-grab slide-list-handle">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-500">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $('#slide-list').sortable({
    handle: '.slide-list-handle',
    axis: 'y',
    update: function(event, ui) {
      const ids = $('#slide-list [data-slide-id]').map(function(index, el) {
        return $(el).data('slide-id');
      }).get();

      $.ajax({
        method: 'POST',
        url: '<%= dashboard_slides_update_path %>',
        data: {
          slides: ids
        }
      });
    }
  });
</script>

app/views/dashboard/sliders/_slider_page.html.erb
<div id="slider-page">
  <% if slider.slides.any? %>

    <div class="flex gap-8 py-8">
      <div class="flex-shrink-0 w-80 flex flex-col" x-data="{ visible: 'images' }">
        <div class="w-full mb-6">
          <button @click="modal = true" type="button" class="w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
            Install Slider
          </button>
        </div>

        <div class="bg-white rounded-md p-4 border border-gray-200 w-full">
          <div class="flex justify-between mb-4">
            <nav class="flex space-x-2">
              <button
                class="text-gray-500 hover:text-gray-700 rounded-md px-2 py-1 text-sm font-medium"
                :class="visible == 'images' ? 'bg-gray-100 text-gray-700' : ''"
                @click="visible = 'images'"
              >
                Slides
              </button>

              <button
                class="text-gray-500 hover:text-gray-700 rounded-md px-2 py-1 text-sm font-medium"
                :class="visible == 'settings' ? 'bg-gray-100 text-gray-700' : ''"
                @click="visible = 'settings'"
              >
                Settings
              </button>
            </nav>
          </div>

          <div>
            <%= render 'settings', slider: slider %>
            <%= render 'slides', slider: slider, slides: slider.slides %>
          </div>
        </div>
      </div>

      <div class="flex-grow flex w-full">
        <div class="bg-white rounded-md p-4 border border-gray-200 flex-grow">
          <%= render 'preview', slider: slider %>
        </div>
      </div>
    </div>

  <% else %>

    <div class="py-10">
      <div class="text-center rounded-lg border-2 border-dashed border-gray-300 p-12 bg-white max-w-lg mx-auto">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="mx-auto h-12 w-12 text-gray-400">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
        </svg>

        <h3 class="mt-2 text-sm font-semibold text-gray-900">Your slideshow will appear here!</h3>
        <p class="mt-1 text-sm text-gray-500">Get started by adding a new slide.</p>
        <div class="mt-6">
          <%= link_to dashboard_sliders_slide_new_path(short_code: slider.short_code), class: 'cursor-pointer inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' do %>
            <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
            </svg>

            New Slide
          <% end %>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/dashboard/sliders/_slides.html.erb
<div id="slides" x-show="visible == 'images'">
  <div class="mb-4">
    <%= link_to 'Add Slide',
        dashboard_sliders_slide_new_path(short_code: slider.short_code),
        class: 'text-center w-full block cursor-pointer rounded-md bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-600 shadow-sm hover:bg-indigo-100'
    %>
  </div>

  <%= render 'slide_list', slides: slides %>
</div>

app/views/dashboard/sliders/_toast.js.erb
<% output = capture do %>
  <div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6">
    <div class="flex w-full flex-col items-center space-y-4 sm:items-end">
      <div class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
        <div class="p-4">
          <div class="flex items-start">
            <div class="flex-shrink-0">
              <svg class="h-6 w-6 text-green-400" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm font-medium text-gray-900">
                <%= text %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

$('#toast').html('<%= j(output) %>')
setTimeout(() => { $('#toast').html('') }, 2000);

app/views/dashboard/sliders/edit.html.erb
<div x-data="{ modal: false }">
  <%= render 'layouts/application/flash_messages' %>
  <%= render 'slider_page', slider: @slider %>
  <%= render 'install', slider: @slider %>
</div>

<div id="loader" class="z-50 fixed top-0 bottom-0 left-0 right-0 items-center justify-center font-medium bg-white/90 hidden">
  Loading...
</div>

app/views/dashboard/sliders/slide_destroy.js.erb
<% slider_page = render('slider_page', slider: @slider) %>
$('#slider-page').replaceWith('<%= j(slider_page) %>');

<%= render 'toast', text: 'Slide removed!' %>

app/views/dashboard/sliders/slides_update.js.erb
<% slider_preview = render 'preview', slider: @slider %>
$('#slider-preview').replaceWith('<%= j(slider_preview) %>');

<%= render 'toast', text: 'Positions saved!' %>

app/views/dashboard/sliders/update.js.erb
<% slider_preview = render 'preview', slider: @slider %>

$('#slider-preview').html('<%= j(slider_preview) %>');

<%= render 'toast', text: 'Settings saved!' %>