config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  # devise_for :users, controllers: {
  #   registrations: 'registrations'
  # }

  root 'pages#home'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'

  get '/sliders/:short_code', to: 'sliders#show'

  namespace :admin do
    resources :sliders, only: [:index, :show]
    resources :request_logs, only: [:index]
    resources :track_logs, only: [:index]
    resources :users, only: [:index] do
      member do
        get 'send_expired_outreach', action: :send_expired_outreach
      end
    end
  end

  namespace :dashboard do
    get '/sliders', to: 'sliders#index'
    get '/sliders/new', to: 'sliders#new', as: :new_slider
    get '/sliders/:short_code', to: 'sliders#edit', as: :edit_slider
    patch '/sliders/:short_code', to: 'sliders#update', as: :update_slider
    delete '/sliders/:short_code', to: 'sliders#destroy', as: :destroy_slider

    post '/sliders/:short_code/slide_create', to: 'sliders#slide_create', as: :slide_create
    get '/sliders/:short_code/slide_destroy/:slide_id', to: 'sliders#slide_destroy', as: :slide_destroy
    post '/sliders/:short_code/slides_update', to: 'sliders#slides_update', as: :slides_update

    get '/sliders/:short_code/slides/new', to: 'sliders/slides#new', as: :sliders_slide_new
    post '/sliders/:short_code/slides', to: 'sliders/slides#create', as: :sliders_slide
    get '/sliders/:short_code/slides/:id', to: 'sliders/slides#edit', as: :sliders_slide_edit
    patch '/sliders/:short_code/slides/:id', to: 'sliders/slides#update', as: :sliders_slide_update

    get '/subscription/checkout', to: 'subscription#checkout', as: :subscription_checkout
    get '/subscription/success', to: 'subscription#success', as: :subscription_success

    resource :account, only: [:show, :update], controller: 'account'
  end

  post '/track', to: 'track#create'
  get '/unsubscribe/:user_id', to: 'unsubscriptions#create', as: :unsubscribe
  get '/unsubscribe/:user_id/success', to: 'unsubscriptions#show', as: :unsubscribe_success

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/slide.rb
# == Schema Information
#
# Table name: slides
#
#  id         :uuid             not null, primary key
#  slider_id  :uuid             not null
#  content    :text
#  weight     :integer          default(0), not null
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  url        :text
#

class Slide < ActiveRecord::Base
  belongs_to :slider
  mount_uploader :image, SlideImageUploader

  validates :image, presence: true

  validates :url, url: {
    allow_blank: true,
    message: 'must include http:// or https://'
  }
end

app/models/slider.rb
# == Schema Information
#
# Table name: sliders
#
#  id                 :uuid             not null, primary key
#  user_id            :uuid
#  title              :string
#  short_code         :string
#  settings           :jsonb
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  request_logs_count :integer          default(0)
#  width              :string           default("1600")
#  height             :string           default("250")
#  mode               :string           default("linear")
#  speed              :string           default("500")
#  auto_enabled       :boolean          default(FALSE)
#  auto_interval      :string           default("2000")
#  controls_enabled   :boolean          default(TRUE)
#  pager_enabled      :boolean          default(TRUE)
#  version            :integer
#  track_logs_count   :integer          default(0)
#
# Indexes
#
#  index_sliders_on_short_code  (short_code) UNIQUE
#

class Slider < ActiveRecord::Base
  has_many :slides, -> { order(weight: :asc) }, dependent: :destroy
  has_many :request_logs
  has_many :track_logs
  belongs_to :user

  before_create :set_short_code

  def self.ransackable_attributes(auth_object = nil)
    ['short_code']
  end

  private

  def set_short_code
    self.short_code = loop do
      random_short_code = ('a'..'z').to_a.shuffle[0,6].join
      break random_short_code unless Slider.exists?(short_code: random_short_code)
    end
  end
end

app/controllers/admin/sliders_controller.rb
class Admin::SlidersController < AdminController
  def index
    @sort = params[:sort] || 'date'
    @direction = params[:dir] || 'desc'

    @sliders = Slider
      .includes(:user)
      .references(:user)
      .where('users.id IS NOT NULL')
      .page(params[:page])
      .per(50)

    if @sort == 'date'
      @sliders = @sliders.order(created_at: @direction)
    elsif @sort == 'requests'
      @sliders = @sliders.order(request_logs_count: @direction)
    elsif @sort == 'tracks'
      @sliders = @sliders.order(track_logs_count: @direction)
    end
  end

  def show
    @slider = Slider.find(params[:id])
    @slides = @slider.slides.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < AdminController
  def index
    @slider = Slider.find(params[:slider_id])
    @slides = @slider.slides.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/dashboard/sliders/slides_controller.rb
class Dashboard::Sliders::SlidesController < DashboardController
  def new
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = Slide.new
  end

  def create
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.new(slide_params)

    if @slide.save
      redirect_to dashboard_edit_slider_path(@slider.short_code), notice: 'Slide created.'
    else
      render :new
    end
  end

  def edit
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.find(params[:id])
  end

  def update
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.find(params[:id])

    if @slide.update(slide_params)
      redirect_to dashboard_edit_slider_path(@slider.short_code), notice: 'Slide updated.'
    else
      render :edit
    end
  end

  private

  def slide_params
    params.require(:slide).permit(:image, :url)
  end
end

app/controllers/dashboard/sliders_controller.rb
class Dashboard::SlidersController < DashboardController
  def index
    @sliders = current_user.sliders
  end

  def edit
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  def update
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slider.update!(slider_params)
  end

  def new
    @slider = current_user.sliders.create!

    redirect_to dashboard_edit_slider_path(@slider.short_code)
  end

  def destroy
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slider.destroy!
    redirect_to dashboard_sliders_path, notice: "Slider #{@slider.short_code} was deleted."
  end

  def slide_destroy
    slide = Slide.find(params[:slide_id])
    slide.destroy!

    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  def slides_update
    params[:slides].each_with_index do |slide_id, index|
      slide = Slide.find(slide_id)

      slide.update!(weight: index)
    end

    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  private

  def slider_params
    params.require(:slider).permit!
  end

  def slide_params
    params.require(:slide).permit(:content, :weight, :image, :slider_id)
  end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  include ActionView::Helpers::TagHelper
  skip_before_action :verify_authenticity_token

  def show
    @short_code = params[:short_code]
    @slider = Slider.find_by(short_code: @short_code)
    @inactive_user = @slider.present? && @slider.user && !@slider.user.active?

    begin
      RequestLog.create!(
        slider: @slider,
        user: @slider.user,
        referrer: request.referrer
      )
    rescue => e
      # Oops.
    end
  end
end

app/views/dashboard/sliders/slides/edit.html.erb
<div class="bg-white rounded-md p-4 border border-gray-200 w-full my-8">
  <h1 class="text-xl font-semibold mb-8">Edit Slide</h1>

  <%= form_for(@slide, url: dashboard_sliders_slide_update_path) do |f| %>
    <div class="space-y-8 w-1/2">
      <div>
        <%= f.label :image, class: 'label mb-2' %>

        <div
          style="background-image: url(<%= @slide.image.url %>)"
          class="w-24 h-16 bg-center bg-cover rounded-md mb-2"
        ></div>

        <%= f.file_field :image, class: 'text-sm' %>

        <% if f.object.errors[:image].present? %>
          <%= render 'dashboard/shared/form_error',
              messages: @slide.errors[:image]
          %>
        <% end %>
      </div>

      <div>
        <%= f.label :url, 'Link (optional)', class: 'label mb-2' %>
        <%= f.text_field :url, class: 'input' %>

        <% if f.object.errors[:url].present? %>
          <%= render 'dashboard/shared/form_error',
              messages: @slide.errors[:url]
          %>
        <% end %>
      </div>

      <div class="flex gap-4">
        <%= f.submit 'Save Slide', class: 'button' %>

        <%= link_to 'Cancel', dashboard_edit_slider_path(@slider.short_code), class: 'button-white' %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).on('submit', 'form', function() {
    $('input[type="submit"]').prop('disabled', true);
  });
</script>

app/views/dashboard/sliders/slides/new.html.erb
<div class="bg-white rounded-md p-4 border border-gray-200 w-full my-8">
  <h1 class="text-xl font-semibold mb-8">New Slide</h1>

  <%= form_for(@slide, url: dashboard_sliders_slide_path) do |f| %>
    <div class="space-y-8 w-1/2">
      <div>
        <%= f.label :image, class: 'label mb-2' %>
        <%= f.file_field :image, class: 'text-sm' %>

        <% if f.object.errors[:image].present? %>
          <%= render 'dashboard/shared/form_error',
              messages: @slide.errors[:image]
          %>
        <% end %>
      </div>

      <div>
        <%= f.label :url, 'Link (optional)', class: 'label mb-2' %>
        <%= f.text_field :url, class: 'input' %>

        <% if f.object.errors[:url].present? %>
          <%= render 'dashboard/shared/form_error',
              messages: @slide.errors[:url]
          %>
        <% end %>
      </div>

      <div class="flex gap-4">
        <%= f.submit 'Save Slide', class: 'button' %>

        <%= link_to 'Cancel', dashboard_edit_slider_path(@slider.short_code), class: 'button-white' %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).on('submit', 'form', function() {
    $('input[type="submit"]').prop('disabled', true);
  });
</script>