config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  # devise_for :users, controllers: {
  #   registrations: 'registrations'
  # }

  root 'pages#home'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'

  get '/sliders/:short_code', to: 'sliders#show'

  namespace :admin do
    resources :sliders, only: [:index, :show]
    resources :request_logs, only: [:index]
    resources :track_logs, only: [:index]
    resources :users, only: [:index] do
      member do
        get 'send_expired_outreach', action: :send_expired_outreach
      end
    end
  end

  namespace :dashboard do
    get '/sliders', to: 'sliders#index'
    get '/sliders/new', to: 'sliders#new', as: :new_slider
    get '/sliders/:short_code', to: 'sliders#edit', as: :edit_slider
    patch '/sliders/:short_code', to: 'sliders#update', as: :update_slider
    delete '/sliders/:short_code', to: 'sliders#destroy', as: :destroy_slider

    post '/sliders/:short_code/slide_create', to: 'sliders#slide_create', as: :slide_create
    get '/sliders/:short_code/slide_destroy/:slide_id', to: 'sliders#slide_destroy', as: :slide_destroy
    post '/sliders/:short_code/slides_update', to: 'sliders#slides_update', as: :slides_update

    get '/sliders/:short_code/slides/new', to: 'sliders/slides#new', as: :sliders_slide_new
    post '/sliders/:short_code/slides', to: 'sliders/slides#create', as: :sliders_slide
    get '/sliders/:short_code/slides/:id', to: 'sliders/slides#edit', as: :sliders_slide_edit
    patch '/sliders/:short_code/slides/:id', to: 'sliders/slides#update', as: :sliders_slide_update

    get '/subscription/checkout', to: 'subscription#checkout', as: :subscription_checkout
    get '/subscription/success', to: 'subscription#success', as: :subscription_success

    resource :account, only: [:show, :update], controller: 'account'
  end

  post '/track', to: 'track#create'
  get '/unsubscribe/:user_id', to: 'unsubscriptions#create', as: :unsubscribe
  get '/unsubscribe/:user_id/success', to: 'unsubscriptions#show', as: :unsubscribe_success

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/controllers/dashboard/account_controller.rb
class Dashboard::AccountController < DashboardController
  def show
  end

  def update
    @user = current_user

    if @user.update(user_params)
      bypass_sign_in(@user)
      redirect_to dashboard_account_path, notice: 'Successfully saved.'
    else
      redirect_to dashboard_account_path, alert: 'Could not save.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/dashboard/sliders/slides_controller.rb
class Dashboard::Sliders::SlidesController < DashboardController
  def new
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = Slide.new
  end

  def create
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.new(slide_params)

    if @slide.save
      redirect_to dashboard_edit_slider_path(@slider.short_code), notice: 'Slide created.'
    else
      render :new
    end
  end

  def edit
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.find(params[:id])
  end

  def update
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slide = @slider.slides.find(params[:id])

    if @slide.update(slide_params)
      redirect_to dashboard_edit_slider_path(@slider.short_code), notice: 'Slide updated.'
    else
      render :edit
    end
  end

  private

  def slide_params
    params.require(:slide).permit(:image, :url)
  end
end

app/controllers/dashboard/sliders_controller.rb
class Dashboard::SlidersController < DashboardController
  def index
    @sliders = current_user.sliders
  end

  def edit
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  def update
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slider.update!(slider_params)
  end

  def new
    @slider = current_user.sliders.create!

    redirect_to dashboard_edit_slider_path(@slider.short_code)
  end

  def destroy
    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slider.destroy!
    redirect_to dashboard_sliders_path, notice: "Slider #{@slider.short_code} was deleted."
  end

  def slide_destroy
    slide = Slide.find(params[:slide_id])
    slide.destroy!

    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  def slides_update
    params[:slides].each_with_index do |slide_id, index|
      slide = Slide.find(slide_id)

      slide.update!(weight: index)
    end

    @slider = current_user.sliders.find_by(short_code: params[:short_code])
    @slides = @slider.slides
  end

  private

  def slider_params
    params.require(:slider).permit!
  end

  def slide_params
    params.require(:slide).permit(:content, :weight, :image, :slider_id)
  end
end

app/controllers/dashboard/subscription_controller.rb
class Dashboard::SubscriptionController < DashboardController
  def checkout
    stripe_portal = Stripe::Checkout::Session.create({
      cancel_url: dashboard_account_url,
      success_url: ENV['APP_HOST'] + '/dashboard/subscription/success?session_id={CHECKOUT_SESSION_ID}',
      line_items: [
        { price: ENV['STRIPE_PRICE_ID'], quantity: 1 },
      ],
      mode: 'payment',
      customer_email: current_user.email
    })

    redirect_to(stripe_portal[:url], allow_other_host: true)
  end

  def success
    stripe_session = Stripe::Checkout::Session.retrieve(params[:session_id])

    current_user.update!(
      stripe_customer_id: stripe_session[:customer],
      stripe_transaction_id: stripe_session[:payment_intent],
      stripe_purchased_at: Time.now,
      status: 'paid'
    )

    begin
      UserMailer.with(user: current_user).payment_success.deliver_now
    rescue => e
      Sentry.capture_exception(e)
    end

    begin
      AdminMailer.with(user: current_user).new_payment.deliver_now
    rescue => e
      Sentry.capture_exception(e)
    end

    redirect_to dashboard_sliders_path, notice: 'Thank you for purchasing SliderUI!'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_subscription

  layout 'dashboard'

  private

  def ensure_subscription
    return if current_user.active?

    @checkout_url = dashboard_subscription_checkout_path
  end
end

app/views/dashboard/shared/_account_nav.html.erb
<div class="account-nav">
  <%= active_link_to 'Subscription', edit_dashboard_subscription_path %>
  <%= active_link_to 'Password', edit_dashboard_password_path %>
  <%= active_link_to 'Delete Account', dashboard_account_path %>
</div>

app/views/dashboard/shared/_form_error.html.erb
<div class="text-sm text-red-600 mt-2">
  <ul>
    <% messages.each do |message| %>
      <li class="list-disc ml-5">
        <%= message %>
      </li>
    <% end %>
  </ul>
</div>

app/views/dashboard/shared/_upgrade.html.erb
<div x-data="{ upgrade: true }">
  <div x-show="upgrade" x-cloak class="relative z-30" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <!--
      Background backdrop, show/hide based on modal state.
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

    <div class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
        <!--
          Modal panel, show/hide based on modal state.
        -->

        <div @click.outside="upgrade = false" class="relative transform overflow-hidden rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-md sm:p-6">
          <div class="absolute right-0 top-0 hidden pr-4 pt-4 sm:block">
            <button @click="upgrade = false" type="button" class="rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
              <span class="sr-only">Close</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <div>
            <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-red-100">
              <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
              </svg>
            </div>
            <div class="mt-3 text-center sm:mt-5">
              <div class="flex flex-col items-center mb-6">
                <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">Your free trial has expired.</h3>
                <p class="text-sm text-gray-500 w-10/12">
                  To continue to use your sliders please upgrade your account with a one-time payment of <span class="text-black font-semibold">$9</span>
                </p>
              </div>

            </div>
          </div>
          <div class="mt-5 sm:mt-6">
            <%= link_to 'Upgrade subscription plan',
                @checkout_url,
                class: 'inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600'
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>